import json
from groq import Groq
from config import GROQ_API_KEY, LLM_MODEL

client = Groq(api_key=GROQ_API_KEY)

def classify_with_llm(text):
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by an AI system.

    Analyze the following text and respond with ONLY a JSON object in this exact format:
    {{"score": <float between 0.0 and 1.0>, "reasoning": "<one sentence explanation>"}}

    Where the score means:
    - 0.0 = almost certainly written by a human
    - 1.0 = almost certainly generated by an AI

    Text to analyze:
    \"\"\"{text}\"\"\"

    Respond with only the JSON object, no other text."""

    response = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()
    result = json.loads(raw)
    return round(float(result["score"]), 4), result.get("reasoning", "")