def generate_label(attribution, confidence):
    score_pct = round(confidence * 100)

    if attribution == "likely_ai":
        return (
            f"⚠️ AI-Generated Content\n"
            f"Our analysis indicates this content was likely generated by an AI system "
            f"(confidence: {score_pct}%). If you are the creator and believe this is "
            f"incorrect, you may submit an appeal."
        )
    elif attribution == "likely_human":
        return (
            f"✅ Human-Authored Content\n"
            f"Our analysis indicates this content was likely written by a human "
            f"(confidence: {score_pct}% human). No further action required."
        )
    else:
        return (
            f"🔍 Authorship Uncertain\n"
            f"Our analysis could not determine with confidence whether this content was "
            f"written by a human or generated by AI (confidence: {score_pct}%). No action "
            f"has been taken."
        )